import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest"
import { setupTestDb, cleanupTestDb } from "./_setup"

beforeAll(() => { setupTestDb() })
afterAll(() => { cleanupTestDb() })

beforeEach(async () => {
  // Reset the secrets-vault key cache so each test sees the same key
  // generated by setupTestDb's SSR_FERNET_KEY_PATH.
  const { _resetCache } = await import("@/lib/secrets-vault")
  _resetCache()
  const { run } = await import("@/lib/db")
  run("DELETE FROM cf_workers_ai_keys")
  run("DELETE FROM cf_keys")
})

describe("encryptExistingAiTokens — boot migration for cf_workers_ai_keys", () => {
  it("converts plaintext rows, leaves enc:v1: rows alone, is idempotent on second run", async () => {
    const { run, all } = await import("@/lib/db")
    const { encrypt } = await import("@/lib/secrets-vault")
    const { encryptExistingAiTokens } = await import("@/lib/repos/cf-ai-keys")

    // Seed: 2 plaintext rows + 1 already-encrypted row.
    run("INSERT INTO cf_workers_ai_keys(account_id, api_token) VALUES(?, ?)", "acct-A", "plain-token-1")
    run("INSERT INTO cf_workers_ai_keys(account_id, api_token) VALUES(?, ?)", "acct-B", "plain-token-2")
    run("INSERT INTO cf_workers_ai_keys(account_id, api_token) VALUES(?, ?)", "acct-C", encrypt("already-encrypted"))

    const r1 = encryptExistingAiTokens()
    expect(r1.converted).toBe(2)
    expect(r1.skipped).toBe(1)

    // Every row now starts with enc:v1:.
    const rows = all<{ account_id: string; api_token: string }>("SELECT account_id, api_token FROM cf_workers_ai_keys")
    expect(rows.length).toBe(3)
    for (const r of rows) {
      expect(r.api_token.startsWith("enc:v1:")).toBe(true)
    }

    // Roundtrip — decrypt yields the original plaintext.
    const { getCfAiKey, listCfAiKeysWithPreview } = await import("@/lib/repos/cf-ai-keys")
    const previews = listCfAiKeysWithPreview()
    expect(previews.length).toBe(3)
    const byAcct = (acct: string) => previews.find((p) => p.account_id === acct)!
    // The preview is computed off the decrypted plaintext, not the ciphertext.
    expect(byAcct("acct-A").token_preview).not.toContain("enc:v1:")
    expect(byAcct("acct-B").token_preview).not.toContain("enc:v1:")

    // getCfAiKey returns plaintext.
    const a = getCfAiKey(byAcct("acct-A").id)
    expect(a?.api_token).toBe("plain-token-1")
    const c = getCfAiKey(byAcct("acct-C").id)
    expect(c?.api_token).toBe("already-encrypted")

    // Second run is a no-op.
    const r2 = encryptExistingAiTokens()
    expect(r2.converted).toBe(0)
    expect(r2.skipped).toBe(3)
  })
})

describe("encryptExistingCfKeys — boot migration for cf_keys", () => {
  it("converts plaintext rows, leaves enc:v1: rows alone, is idempotent on second run", async () => {
    const { run, all } = await import("@/lib/db")
    const { encrypt } = await import("@/lib/secrets-vault")
    const { encryptExistingCfKeys, listCfKeysWithPreview } = await import("@/lib/repos/cf-keys")

    run("INSERT INTO cf_keys(email, api_key) VALUES(?, ?)", "alice@example.com", "plain-cf-key-1")
    run("INSERT INTO cf_keys(email, api_key) VALUES(?, ?)", "bob@example.com", "plain-cf-key-2")
    run("INSERT INTO cf_keys(email, api_key) VALUES(?, ?)", "carol@example.com", encrypt("already-enc"))

    const r1 = encryptExistingCfKeys()
    expect(r1.converted).toBe(2)
    expect(r1.skipped).toBe(1)

    const rows = all<{ email: string; api_key: string }>("SELECT email, api_key FROM cf_keys")
    for (const r of rows) {
      expect(r.api_key.startsWith("enc:v1:")).toBe(true)
    }

    // listCfKeysWithPreview computes the preview off the decrypted plaintext.
    const previews = listCfKeysWithPreview()
    const byEmail = (e: string) => previews.find((p) => p.email === e)!
    expect(byEmail("alice@example.com").key_preview).not.toContain("enc:v1:")
    expect(byEmail("bob@example.com").key_preview).not.toContain("enc:v1:")

    // Second run is a no-op.
    const r2 = encryptExistingCfKeys()
    expect(r2.converted).toBe(0)
    expect(r2.skipped).toBe(3)
  })
})
